fail()

async function fail() {
  throw new Error('fail')
}
